name: Build Releases

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact: Indium-linux

          - os: windows-latest
            artifact: Indium-windows

          - os: macos-latest
            artifact: Indium-macos

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # For Linux
      - name: Install Linux deps
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y \
            cmake \
            ninja-build \
            build-essential \
            libraylib-dev

      # For Windows
      - name: Setup MSYS2
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          install: >
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-ninja
            mingw-w64-ucrt-x86_64-raylib

      # For macOS
      - name: Install macOS deps
        if: runner.os == 'macOS'
        run: |
          brew install raylib cmake ninja

      # BUILD LINUX/MAC
      - name: Build Unix
        if: runner.os != 'Windows'
        run: |
          chmod +x run.sh
          ./run.sh --no-run

      # Build For Windows
      - name: Build Windows
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          chmod +x run-windows.sh
          ./run-windows.sh --no-run

      - name: Package
        run: |
          mkdir out

          if [ "$RUNNER_OS" = "Windows" ]; then
            cp build-windows/Indium.exe out/
          else
            cp build/Indium out/
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: out/*
